language: php
php:
  - hhvm

before_script:
  - composer self-update
  - composer update
  
script:
  - hh_client
  - hhvm test/run_tests.php
  - hhvm examples/dorm/codegen.php examples/dorm/demo/DormUserSchema.php

